RUN wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/VictorMono.zip && \
sudo mkdir -p /usr/share/fonts && \
sudo unzip VictorMono.zip -d /usr/share/fonts && \
sudo fc-cache -f -v
